name: Build Lazarus Artifact

on: 
  push:
    branches: 
      - master
      
env:
  LAZARUS_VERSION: "2.0.10"

jobs:
  setup:
    name: Checkout Source
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'        

      - name: Download Lazarus
        run:  scripts/setup_lazarus.sh


  build:
    name: Building the artifact
    runs-on: self-hosted
    container:
      image: epidata/fpcbuild:3.2.0-12
      volumes:
        - /home/runner/.m2/settings.xml:/etc/maven/settings.xml
    needs: setup

    steps:
      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'
                    

      - name: Compile Linux
        run:  mvn compile -Plinux64

      - name: Compile Windows
        run:  mvn compile -Pwin64

      - name: Compile Mac
        run:  mvn compile -Pdarwin64

  deploy:
    name: Deploy Artifact
    runs-on: self-hosted
    needs: build

    steps:
      - name: Deploy
        run: |
          mvn versions:set -DnewVersion=${LAZARUS_VERSION} -f deploy.pom.xml
          mvn deploy -f deploy.pom.xml
          scripts/remove_lazarus.sh
