name: Build Lazarus Artifact

on: push

env:
  LAZARUS_VERSION: "2.0.10"

jobs:
  scm:
    name: Checkout Source
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Resolve Parent Range
        run: |
          mvn versions:resolve-ranges -f pom.xml
          mvn versions:resolve-ranges -f deploy.pom.xml

  fetch:
    name: Fetch Lazarus Sources
    runs-on: self-hosted
    needs: scm

    steps:
      - name: Download Lazarus
        run:  scripts/setup_lazarus.sh


  build:
    name: Building the artifact
    runs-on: self-hosted
    container:
      image: epidata/fpcbuild:3.2.0-12
    needs: [scm, fetch]

    steps:
      - name: Compile Linux
        run:  mvn compile -Plinux64
