name: Build Lazarus Artifact

on: 
  pull_request:
    branches: 
      - master
      
env:
  LAZARUS_VERSION: "2.0.10"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers:
            '[{
            "id": "github",
            "username": "${{ secrets.CI_USER }}",
            "password": "${{ secrets.CI_PASSWORD }}"
            }]'
          repositories:
            '[
              {
                "id": "central",
                "url": "https://repo1.maven.org/maven2"
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/epidata-dk/parent/",
                "snapshots": {
                  "enabled": "true"
                }                
              }
            ]'

      - name: Copy settings file
        run: cp /home/runner/.m2/settings.xml /tmp/settings.xml


      - name: Download Lazarus
        run:  scripts/setup_lazarus.sh

  build:
    name: Compile the source
    runs-on: ubuntu-latest
    container:
      image: epidata/fpcbuild:3.2.0-12
      volumes:
        - /tmp/settings.xml:/etc/maven/settings.xml
    needs: setup

    steps:
      - name: Compile Linux
        run:  mvn compile -Plinux64

      - name: Compile Windows
        run:  mvn compile -Pwin64

      - name: Compile Mac
        run:  mvn compile -Pdarwin64